# Generated by Django 6.0.1 on 2026-07-13 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentpage',
            name='body_en',
        ),
        migrations.RemoveField(
            model_name='contentpage',
            name='body_ru',
        ),
        migrations.RemoveField(
            model_name='contentpage',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='contentpage',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='place',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='place',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='place',
            name='distance_comment_en',
        ),
        migrations.RemoveField(
            model_name='place',
            name='distance_comment_ru',
        ),
        migrations.RemoveField(
            model_name='place',
            name='info_link_en',
        ),
        migrations.RemoveField(
            model_name='place',
            name='info_link_ru',
        ),
        migrations.RemoveField(
            model_name='place',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='place',
            name='name_ru',
        ),
    ]
