# Generated by Django 6.0.1 on 2026-08-03 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0003_contentpage_body_en_contentpage_body_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='cropping_blur',
        ),
        migrations.RemoveField(
            model_name='image',
            name='cropping_main',
        ),
        migrations.RemoveField(
            model_name='image',
            name='cropping_small',
        ),
    ]
