# Generated by Django 6.0.1 on 2026-08-03 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0005_image_cropping_blur_image_cropping_main_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='test/')),
            ],
        ),
    ]
