# Generated by Django 6.0.1 on 2026-08-03 11:25

import image_cropping.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0006_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='cropping_blur',
            field=image_cropping.fields.ImageRatioField('image_full', '100x100', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping blur'),
        ),
        migrations.AlterField(
            model_name='image',
            name='cropping_main',
            field=image_cropping.fields.ImageRatioField('image_full', '1280x1280', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping main'),
        ),
        migrations.AlterField(
            model_name='image',
            name='cropping_small',
            field=image_cropping.fields.ImageRatioField('image_full', '600x600', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping small'),
        ),
    ]
