# Generated by Django 6.0.1 on 2026-08-04 13:20

import image_cropping.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0007_alter_image_cropping_blur_alter_image_cropping_main_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='cropping_blur',
        ),
        migrations.AddField(
            model_name='image',
            name='cropping_tiny',
            field=image_cropping.fields.ImageRatioField('image_full', '100x100', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping tiny'),
        ),
    ]
