# Generated by Django 6.0.1 on 2026-08-04 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0008_remove_image_cropping_blur_image_cropping_tiny'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
