# Generated by Django 6.0.1 on 2026-08-05 12:02

import image_cropping.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0009_delete_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='test/')),
            ],
        ),
        migrations.RemoveField(
            model_name='image',
            name='cropping_tiny',
        ),
        migrations.AddField(
            model_name='image',
            name='cropping_blur',
            field=image_cropping.fields.ImageRatioField('image_full', '100x100', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping blur'),
        ),
    ]
