# Generated by Django 6.0.1 on 2026-03-12 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='unique name (lower case without spaces)', unique=True, verbose_name='slug')),
                ('name', models.CharField(max_length=80, verbose_name='Room name')),
                ('name_en', models.CharField(max_length=80, null=True, verbose_name='Room name')),
                ('name_ru', models.CharField(max_length=80, null=True, verbose_name='Room name')),
                ('adults_num', models.IntegerField(help_text='places in the room for any guests (adult or children)', verbose_name='Adults')),
                ('children_num', models.IntegerField(help_text='places in the room only for children', verbose_name='Children')),
                ('beds', models.TextField(default='', max_length=255)),
                ('price', models.IntegerField(default=5000)),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now=True, verbose_name='created at')),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('validated', 'Validated'), ('confirmed', 'Confirmed')], default='requested', max_length=20)),
                ('guest_name', models.CharField(verbose_name='Guest name')),
                ('email', models.EmailField(default=None, max_length=254)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('nights', models.PositiveIntegerField()),
                ('message', models.TextField(default='', max_length=255)),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'base_manager_name': 'objects',
                'default_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='RoomReserved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adults', models.IntegerField(default=0, verbose_name='adult places reserved')),
                ('children', models.IntegerField(default=0, verbose_name='children places reserved')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms_reserved', related_query_name='room_reserved', to='main.reservation')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.room')),
            ],
            options={
                'verbose_name': 'Reserved room',
                'verbose_name_plural': 'Reserved rooms',
            },
        ),
    ]
