# Generated by Django 5.2.4 on 2026-01-25 11:32

import django.db.models.deletion
import django.db.models.manager
import image_cropping.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(choices=[('about', 'About'), ('service', 'Service'), ('location', 'Location'), ('places', 'Places of interest'), ('rooms-preview', 'Rooms')], help_text='unique name (lower case without spaces)', unique=True, verbose_name='slug')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Content page title')),
                ('title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Content page title')),
                ('title_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Content page title')),
                ('body', models.TextField(help_text='Write the content in Markdown fromat.', verbose_name='Content page body')),
                ('body_en', models.TextField(help_text='Write the content in Markdown fromat.', null=True, verbose_name='Content page body')),
                ('body_ru', models.TextField(help_text='Write the content in Markdown fromat.', null=True, verbose_name='Content page body')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Content page',
                'verbose_name_plural': 'Content pages',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveBigIntegerField(default=0)),
                ('image_full', models.ImageField(upload_to='static/img/full')),
                ('cropping_main', image_cropping.fields.ImageRatioField('image', '1280x853', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping main')),
                ('cropping_small', image_cropping.fields.ImageRatioField('image', '600x400', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping small')),
                ('cropping_blur', image_cropping.fields.ImageRatioField('image', '20x13', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping blur')),
            ],
            options={
                'verbose_name': 'image',
                'verbose_name_plural': 'images',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ImageTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'image tag',
                'verbose_name_plural': 'image tags',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63, unique=True, verbose_name='name')),
                ('slug', models.CharField(help_text='unique name (lower case without spaces)', max_length=30, unique=True, verbose_name='slug')),
                ('distance', models.FloatField(help_text='distance')),
                ('distance_comment', models.CharField(blank=True, default='', max_length=255, verbose_name='distance comment')),
                ('description', models.TextField(verbose_name='description')),
                ('geoloc', models.CharField(help_text='link to a map provider with the location of the place', verbose_name='geolocation link')),
                ('info_link', models.CharField(blank=True, help_text='Link to an external resources with information about the place', verbose_name='Information link')),
            ],
            options={
                'verbose_name': 'place',
                'verbose_name_plural': 'places',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='unique name (lower case without spaces)', unique=True, verbose_name='slug')),
                ('name', models.CharField(max_length=80, verbose_name='Room name')),
                ('name_en', models.CharField(max_length=80, null=True, verbose_name='Room name')),
                ('name_ru', models.CharField(max_length=80, null=True, verbose_name='Room name')),
                ('adults_num', models.IntegerField(help_text='places in the room for any guests (adult or children)', verbose_name='Adults')),
                ('children_num', models.IntegerField(help_text='places in the room only for children', verbose_name='Children')),
                ('beds', models.TextField(default='', max_length=255)),
                ('price', models.IntegerField(default=5000)),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('validated', 'Validated'), ('confirmed', 'Confirmed')], default='requested', max_length=20)),
                ('guest_name', models.CharField(verbose_name='Guest name')),
                ('email', models.EmailField(default=None, max_length=254)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('nights', models.PositiveIntegerField()),
                ('message', models.TextField(default='', max_length=255)),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            managers=[
                ('confirmed', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='RoomReserved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adults', models.IntegerField(default=0, verbose_name='adult places reserved')),
                ('children', models.IntegerField(default=0, verbose_name='children places reserved')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms_reserved', related_query_name='room_reserved', to='main.reservation')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.room')),
            ],
            options={
                'verbose_name': 'Reserved room',
                'verbose_name_plural': 'Reserved rooms',
            },
        ),
        migrations.CreateModel(
            name='PlaceImage',
            fields=[
                ('image_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.image')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', related_query_name='images', to='main.place', verbose_name='place')),
            ],
            options={
                'verbose_name': 'place image',
                'verbose_name_plural': 'place images',
            },
            bases=('main.image',),
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('image_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.image')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', related_query_name='images', to='main.room')),
            ],
            options={
                'verbose_name': 'room image',
                'verbose_name_plural': 'room images',
            },
            bases=('main.image',),
        ),
        migrations.CreateModel(
            name='WideImage',
            fields=[
                ('image_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.image')),
                ('tag', models.ManyToManyField(blank=True, to='main.imagetag')),
            ],
            options={
                'verbose_name': 'wide photo',
                'verbose_name_plural': 'wide photos',
            },
            bases=('main.image',),
        ),
    ]
