# Generated by Django 5.2.4 on 2025-10-27 07:31

import django.db.models.deletion
import image_cropping.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Content_slug_helptext', unique=True, verbose_name='Content_slug')),
                ('title', models.CharField(max_length=255, verbose_name='Content_page_title')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Content_page_title')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Content_page_title')),
                ('body', models.TextField(help_text='Write the content in Markdown fromat.', verbose_name='Content_page_body')),
                ('body_en', models.TextField(help_text='Write the content in Markdown fromat.', null=True, verbose_name='Content_page_body')),
                ('body_ru', models.TextField(help_text='Write the content in Markdown fromat.', null=True, verbose_name='Content_page_body')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Content_page',
                'verbose_name_plural': 'Content_pages',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveBigIntegerField(default=0)),
                ('image_full', models.ImageField(upload_to='static/img/full')),
                ('cropping_main', image_cropping.fields.ImageRatioField('image', '1280x853', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping main')),
                ('cropping_small', image_cropping.fields.ImageRatioField('image', '600x400', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping small')),
                ('cropping_blur', image_cropping.fields.ImageRatioField('image', '20x13', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping blur')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Room_slug_helptext', unique=True, verbose_name='Room_slug')),
                ('name', models.CharField(max_length=255, verbose_name='Room_name')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Room_name')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Room_name')),
                ('adults_num', models.IntegerField(verbose_name='Room_adults_num')),
                ('children_num', models.IntegerField(verbose_name='Room_children_num')),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
            },
        ),
        migrations.AlterField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reservation',
            name='rooms',
            field=models.ManyToManyField(to='main.room'),
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('image_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.image')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', related_query_name='images', to='main.room')),
            ],
            bases=('main.image',),
        ),
    ]
