# Generated by Django 5.2.4 on 2026-01-04 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('validated', 'Validated'), ('confirmed', 'Confirmed')], default='requested', max_length=20),
        ),
        migrations.AlterField(
            model_name='roomreserved',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms_reserved', related_query_name='room_reserved', to='main.reservation'),
        ),
    ]
