# Generated by Django 5.2.4 on 2025-10-24 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=255, verbose_name='Content_page_title')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Content_page_title')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Content_page_title')),
                ('body', models.TextField(help_text='Write the content in Markdown fromat.', verbose_name='Content_page_body')),
                ('body_en', models.TextField(help_text='Write the content in Markdown fromat.', null=True, verbose_name='Content_page_body')),
                ('body_ru', models.TextField(help_text='Write the content in Markdown fromat.', null=True, verbose_name='Content_page_body')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Content_page',
                'verbose_name_plural': 'Content_pages',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255, null=True)),
                ('name_ru', models.CharField(max_length=255, null=True)),
                ('adults_num', models.IntegerField()),
                ('children_num', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
            },
        ),
        migrations.AlterField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reservation',
            name='rooms',
            field=models.ManyToManyField(to='main.room'),
        ),
    ]
