# Generated by Django 6.0.1 on 2026-07-13 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='room',
            name='name_ru',
        ),
    ]
