# Generated by Django 6.0.1 on 2026-02-04 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_imagetag_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='description_en',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='place',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='place',
            name='distance_comment_en',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='distance comment'),
        ),
        migrations.AddField(
            model_name='place',
            name='distance_comment_ru',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='distance comment'),
        ),
        migrations.AddField(
            model_name='place',
            name='info_link_en',
            field=models.CharField(blank=True, help_text='Link to an external resources with information about the place', null=True, verbose_name='Information link'),
        ),
        migrations.AddField(
            model_name='place',
            name='info_link_ru',
            field=models.CharField(blank=True, help_text='Link to an external resources with information about the place', null=True, verbose_name='Information link'),
        ),
        migrations.AddField(
            model_name='place',
            name='name_en',
            field=models.CharField(max_length=63, null=True, unique=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='place',
            name='name_ru',
            field=models.CharField(max_length=63, null=True, unique=True, verbose_name='name'),
        ),
    ]
