# Generated by Django 5.2.4 on 2025-11-05 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_contentpage_image_room_alter_reservation_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.CharField(max_length=255, unique=True)),
                ('distance', models.FloatField(help_text='Distance from the house to the place in kilometers')),
            ],
        ),
        migrations.CreateModel(
            name='PlaceImage',
            fields=[
                ('image_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.image')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', related_query_name='images', to='main.place')),
            ],
            bases=('main.image',),
        ),
    ]
