# Generated by Django 5.2.4 on 2025-10-24 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_contentpage_room_alter_reservation_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentpage',
            name='slug',
            field=models.SlugField(help_text='Content_slug_helptext', unique=True, verbose_name='Content_slug'),
        ),
        migrations.AlterField(
            model_name='room',
            name='adults_num',
            field=models.IntegerField(verbose_name='Room_adults_num'),
        ),
        migrations.AlterField(
            model_name='room',
            name='children_num',
            field=models.IntegerField(verbose_name='Room_children_num'),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Room_name'),
        ),
        migrations.AlterField(
            model_name='room',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Room_name'),
        ),
        migrations.AlterField(
            model_name='room',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Room_name'),
        ),
        migrations.AlterField(
            model_name='room',
            name='slug',
            field=models.SlugField(help_text='Room_slug_helptext', unique=True, verbose_name='Room_slug'),
        ),
    ]
