# Generated by Django 6.0.1 on 2026-07-13 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_room_name_en_remove_room_name_ru'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='name_en',
            field=models.CharField(max_length=80, null=True, verbose_name='Room name'),
        ),
        migrations.AddField(
            model_name='room',
            name='name_ru',
            field=models.CharField(max_length=80, null=True, verbose_name='Room name'),
        ),
    ]
