# Generated by Django 5.2.4 on 2025-11-22 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_contentpage_image_place_room_alter_reservation_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wideimage',
            name='original',
        ),
        migrations.AddField(
            model_name='room',
            name='price',
            field=models.IntegerField(default=5000),
        ),
    ]
