# Generated by Django 5.2.4 on 2026-01-19 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_reservation_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='place',
            name='distance_comment',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='distance_comment'),
        ),
        migrations.AlterField(
            model_name='place',
            name='slug',
            field=models.CharField(help_text='slug_helptext', max_length=30, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='room',
            name='beds',
            field=models.TextField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=80, verbose_name='Room_name'),
        ),
        migrations.AlterField(
            model_name='room',
            name='name_en',
            field=models.CharField(max_length=80, null=True, verbose_name='Room_name'),
        ),
        migrations.AlterField(
            model_name='room',
            name='name_ru',
            field=models.CharField(max_length=80, null=True, verbose_name='Room_name'),
        ),
        migrations.AddField(
            model_name='wideimage',
            name='set_name',
            field=models.ManyToManyField(blank=True, to='main.imagetag'),
        ),
    ]
