# Generated by Django 5.2.4 on 2025-11-26 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_wideimage_original_room_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentpage',
            name='slug',
            field=models.SlugField(choices=[('about', 'About'), ('service', 'Service'), ('location', 'Location'), ('places', 'Places of interest'), ('room-preview', 'Rooms')], help_text='slug_helptext', unique=True, verbose_name='slug'),
        ),
    ]
