# Generated by Django 6.0.1 on 2026-07-17 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_room_name_en_room_name_ru'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('validated', 'Validated'), ('confirmed', 'Confirmed'), ('declined', 'Declined')], default='requested', max_length=20),
        ),
    ]
