# Generated by Django 5.2.4 on 2025-11-06 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_place_placeimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name': 'place', 'verbose_name_plural': 'places'},
        ),
        migrations.AlterModelOptions(
            name='placeimage',
            options={'verbose_name': 'place image', 'verbose_name_plural': 'place images'},
        ),
        migrations.AddField(
            model_name='place',
            name='description',
            field=models.TextField(default='', max_length=511, verbose_name='description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='distance_comment',
            field=models.TextField(default='', max_length=63, verbose_name='distance_comment'),
        ),
        migrations.AddField(
            model_name='roomimage',
            name='beds',
            field=models.TextField(default='', max_length=63),
        ),
        migrations.AlterField(
            model_name='contentpage',
            name='slug',
            field=models.SlugField(help_text='slug_helptext', unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='place',
            name='distance',
            field=models.FloatField(help_text='distance'),
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(max_length=63, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='place',
            name='slug',
            field=models.CharField(help_text='slug_helptext', max_length=63, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='placeimage',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', related_query_name='images', to='main.place', verbose_name='place'),
        ),
        migrations.AlterField(
            model_name='room',
            name='slug',
            field=models.SlugField(help_text='slug_helptext', unique=True, verbose_name='slug'),
        ),
    ]
