# Generated by Django 5.2.4 on 2026-01-19 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_imagetag_alter_place_distance_comment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wideimage',
            old_name='set_name',
            new_name='tag',
        ),
    ]
