# Generated by Django 5.2.4 on 2025-10-25 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_image_roomimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='image_full',
        ),
    ]
