# Generated by Django 5.2.4 on 2025-12-20 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_contentpage_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomReserved',
            fields=[
                ('room_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.room')),
                ('adults', models.IntegerField(default=0, verbose_name='adults reserved')),
                ('children', models.IntegerField(default=0, verbose_name='children_reserved')),
            ],
            options={
                'verbose_name': 'Reserved room',
                'verbose_name_plural': 'Reserved rooms',
            },
            bases=('main.room',),
        ),
        migrations.AlterField(
            model_name='room',
            name='adults_num',
            field=models.IntegerField(help_text='places in the room for any guest (adult or children)', verbose_name='Room_adults_num'),
        ),
        migrations.AlterField(
            model_name='room',
            name='children_num',
            field=models.IntegerField(help_text='places in the room only for children', verbose_name='Room_children_num'),
        ),
    ]
