# Generated by Django 5.2.4 on 2025-11-06 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_place_options_alter_placeimage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
    ]
