# Generated by Django 5.2.4 on 2026-01-19 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_set_name_wideimage_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagetag',
            options={'verbose_name': 'image tag', 'verbose_name_plural': 'image tags'},
        ),
        migrations.AlterField(
            model_name='contentpage',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Content_page_title'),
        ),
        migrations.AlterField(
            model_name='contentpage',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Content_page_title'),
        ),
        migrations.AlterField(
            model_name='contentpage',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Content_page_title'),
        ),
    ]
