# Generated by Django 5.2.4 on 2025-10-26 07:19

import image_cropping.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_image_image_image_full'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomimage',
            name='cropping_blur',
            field=image_cropping.fields.ImageRatioField('image', '20x13', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping blur'),
        ),
        migrations.AddField(
            model_name='roomimage',
            name='cropping_main',
            field=image_cropping.fields.ImageRatioField('image', '1200x800', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping main'),
        ),
        migrations.AddField(
            model_name='roomimage',
            name='cropping_small',
            field=image_cropping.fields.ImageRatioField('image', '688x388', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping small'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_full',
            field=models.ImageField(upload_to='static/img/full'),
        ),
    ]
