# Generated by Django 5.2.4 on 2025-11-06 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_place_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='distance_comment',
            field=models.TextField(blank=True, default='', max_length=63, verbose_name='distance_comment'),
        ),
    ]
