# Generated by Django 6.0.1 on 2026-07-21 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_reservation_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'base_manager_name': 'objects', 'default_manager_name': 'objects', 'verbose_name': 'reservation'},
        ),
        migrations.AlterField(
            model_name='roomreserved',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms_reserved', related_query_name='room_reserved', to='main.room'),
        ),
    ]
