# Generated by Django 5.2.4 on 2025-12-20 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_roomreserved_alter_room_adults_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='rooms',
            field=models.ManyToManyField(to='main.roomreserved'),
        ),
    ]
