# Generated by Django 5.2.4 on 2026-01-19 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_imagetag_options_alter_contentpage_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentpage',
            name='slug',
            field=models.SlugField(choices=[('about', 'About'), ('service', 'Service'), ('location', 'Location'), ('places', 'Places of interest'), ('rooms-preview', 'Rooms')], help_text='slug_helptext', unique=True, verbose_name='slug'),
        ),
    ]
