# Generated by Django 5.2.4 on 2026-01-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_contentpage_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='guest_name',
            field=models.CharField(default='test guest name', verbose_name='Guest name'),
            preserve_default=False,
        ),
    ]
