# Generated by Django 5.2.4 on 2025-11-09 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_place_distance_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomimage',
            name='beds',
        ),
        migrations.AddField(
            model_name='room',
            name='beds',
            field=models.TextField(default='', max_length=63),
        ),
    ]
