# Generated by Django 5.2.4 on 2025-10-26 08:36

import image_cropping.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_image_cropping_blur_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomimage',
            name='cropping_blur',
        ),
        migrations.RemoveField(
            model_name='roomimage',
            name='cropping_main',
        ),
        migrations.RemoveField(
            model_name='roomimage',
            name='cropping_small',
        ),
        migrations.AddField(
            model_name='image',
            name='cropping_blur',
            field=image_cropping.fields.ImageRatioField('image_full', '20x13', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping blur'),
        ),
        migrations.AddField(
            model_name='image',
            name='cropping_main',
            field=image_cropping.fields.ImageRatioField('image_full', '1200x800', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping main'),
        ),
        migrations.AddField(
            model_name='image',
            name='cropping_small',
            field=image_cropping.fields.ImageRatioField('image_full', '688x388', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping small'),
        ),
    ]
