# Generated by Django 5.2.4 on 2025-10-26 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_simpleimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SimpleImage',
        ),
        migrations.RemoveField(
            model_name='roomimage',
            name='cropping_blur',
        ),
        migrations.RemoveField(
            model_name='roomimage',
            name='cropping_main',
        ),
        migrations.RemoveField(
            model_name='roomimage',
            name='cropping_small',
        ),
    ]
