# Generated by Django 5.2.4 on 2025-10-26 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_delete_simpleimage_remove_roomimage_cropping_blur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_blur',
            field=models.CharField(default=''),
        ),
        migrations.AddField(
            model_name='image',
            name='image_small',
            field=models.CharField(default=''),
        ),
    ]
