# Generated by Django 5.2.4 on 2025-10-26 15:28

import image_cropping.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_image_image_blur_image_image_small'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_blur',
        ),
        migrations.RemoveField(
            model_name='image',
            name='image_small',
        ),
        migrations.AddField(
            model_name='image',
            name='cropping_blur',
            field=image_cropping.fields.ImageRatioField('image', '20x13', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping blur'),
        ),
        migrations.AddField(
            model_name='image',
            name='cropping_main',
            field=image_cropping.fields.ImageRatioField('image', '1280x853', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping main'),
        ),
        migrations.AddField(
            model_name='image',
            name='cropping_small',
            field=image_cropping.fields.ImageRatioField('image', '600x400', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping small'),
        ),
    ]
