# Generated by Django 6.0.1 on 2026-07-13 10:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationDemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now=True, verbose_name='created at')),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('validated', 'Validated'), ('confirmed', 'Confirmed')], default='requested', max_length=20)),
                ('guest_name', models.CharField(verbose_name='Guest name')),
                ('email', models.EmailField(default=None, max_length=254)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('nights', models.PositiveIntegerField()),
                ('message', models.TextField(default='', max_length=255)),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
                'default_manager_name': 'objects',
            },
        ),
    ]
