# Generated by Django 6.0.1 on 2026-08-05 12:19

import image_cropping.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagedemo',
            name='cropping_blur',
        ),
        migrations.AddField(
            model_name='imagedemo',
            name='cropping_tiny',
            field=image_cropping.fields.ImageRatioField('image_full', '100x100', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping tiny'),
        ),
    ]
