# Generated by Django 6.0.1 on 2026-07-13 12:36

import image_cropping.fields
import site_content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageDemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveBigIntegerField(default=0)),
                ('image_full', models.ImageField(upload_to=site_content.models.get_upload_path)),
                ('cropping_main', image_cropping.fields.ImageRatioField('image', '1280x1280', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping main')),
                ('cropping_small', image_cropping.fields.ImageRatioField('image', '600x600', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping small')),
                ('cropping_blur', image_cropping.fields.ImageRatioField('image', '100x100', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping blur')),
            ],
            options={
                'verbose_name': 'image',
                'verbose_name_plural': 'images',
                'ordering': ['order'],
                'abstract': False,
            },
        ),
    ]
