# Generated by Django 6.0.1 on 2026-07-13 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_imagedemo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentPageDemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.TextField(choices=[('about', 'About'), ('service', 'Service'), ('location', 'Location'), ('places', 'Places of interest'), ('rooms-preview', 'Rooms'), ('contacts', 'Contacts'), ('additional', 'Additional')], default='additional', help_text='content tag to help udentify what it is for', verbose_name='tag')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Content page title')),
                ('body', models.TextField(verbose_name='Content page body')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Content page',
                'verbose_name_plural': 'Content pages',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImageGridDemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField(default=None, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImageTagDemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name': 'image tag',
                'verbose_name_plural': 'image tags',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlaceDemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63, unique=True, verbose_name='name')),
                ('slug', models.CharField(help_text='unique name (lower case without spaces)', max_length=30, unique=True, verbose_name='slug')),
                ('distance', models.FloatField(help_text='distance')),
                ('distance_comment', models.CharField(blank=True, default='', max_length=255, verbose_name='distance comment')),
                ('description', models.TextField(verbose_name='description')),
                ('geoloc', models.CharField(help_text='link to a map provider with the location of the place', verbose_name='geolocation link')),
                ('info_link', models.CharField(blank=True, help_text='Link to an external resources with information about the place', verbose_name='Information link')),
            ],
            options={
                'verbose_name': 'place',
                'verbose_name_plural': 'places',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RoomDemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='unique name (lower case without spaces)', unique=True, verbose_name='slug')),
                ('name', models.CharField(max_length=80, verbose_name='Room name')),
                ('adults_num', models.IntegerField(help_text='places in the room for any guests (adult or children)', verbose_name='Adults')),
                ('children_num', models.IntegerField(help_text='places in the room only for children', verbose_name='Children')),
                ('beds', models.TextField(default='', max_length=255)),
                ('price', models.IntegerField(default=5000)),
                ('description', models.TextField(default='', max_length=255)),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GridImageDemo',
            fields=[
                ('imagedemo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='demo.imagedemo')),
                ('format_in_grid', models.TextField(blank=True, choices=[('wide', 'Wide'), ('medium', 'Album medium'), ('portrait', 'Protrait medium'), ('small', 'Album small')], help_text='Which frame format this image is for inside the mosaic image grid')),
                ('grid', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grid_image', related_query_name='grid_images', to='demo.imagedemo')),
                ('tag', models.ManyToManyField(blank=True, to='demo.imagetagdemo')),
            ],
            options={
                'verbose_name': 'grid image',
                'verbose_name_plural': 'grid images',
            },
            bases=('demo.imagedemo',),
        ),
        migrations.CreateModel(
            name='PlaceImageDemo',
            fields=[
                ('imagedemo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='demo.imagedemo')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', related_query_name='images', to='demo.placedemo', verbose_name='place')),
            ],
            options={
                'verbose_name': 'place image',
                'verbose_name_plural': 'place images',
            },
            bases=('demo.imagedemo',),
        ),
        migrations.CreateModel(
            name='RoomImageDemo',
            fields=[
                ('imagedemo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='demo.imagedemo')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', related_query_name='images', to='demo.roomdemo')),
            ],
            options={
                'verbose_name': 'room image',
                'verbose_name_plural': 'room images',
            },
            bases=('demo.imagedemo',),
        ),
        migrations.CreateModel(
            name='RoomReservedDemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adults', models.IntegerField(default=0, verbose_name='adult places reserved')),
                ('children', models.IntegerField(default=0, verbose_name='children places reserved')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms_reserved', related_query_name='room_reserved', to='demo.reservationdemo')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.roomdemo')),
            ],
            options={
                'verbose_name': 'Reserved room',
                'verbose_name_plural': 'Reserved rooms',
            },
        ),
        migrations.CreateModel(
            name='WideImageDemo',
            fields=[
                ('imagedemo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='demo.imagedemo')),
                ('tag', models.ManyToManyField(blank=True, to='demo.imagetagdemo')),
            ],
            options={
                'verbose_name': 'wide photo',
                'verbose_name_plural': 'wide photos',
            },
            bases=('demo.imagedemo',),
        ),
    ]
