# Generated by Django 6.0.1 on 2026-07-14 09:34

import site_content.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_contentpagedemo_body_en_contentpagedemo_body_ru_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewDemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='review date')),
                ('rating', models.FloatField(validators=[site_content.validators.validate_rating_value])),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name': 'reviews',
                'abstract': False,
            },
        ),
    ]
