# Generated by Django 6.0.1 on 2026-07-14 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0005_reviewdemo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlaceImageDemo',
            new_name='PlaceImage',
        ),
    ]
