# Generated by Django 6.0.1 on 2026-07-14 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0006_rename_placeimagedemo_placeimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlaceImage',
            new_name='PlaceImageDemo',
        ),
    ]
