# Generated by Django 6.0.1 on 2026-07-20 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0008_alter_reservationdemo_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservationdemo',
            options={'base_manager_name': 'objects', 'default_manager_name': 'objects', 'verbose_name': 'reservation'},
        ),
    ]
