# Generated by Django 6.0.1 on 2026-07-27 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0009_alter_reservationdemo_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gridimagedemo',
            name='grid',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grid_image', related_query_name='grid_images', to='demo.imagegriddemo'),
        ),
    ]
