# Generated by Django 6.0.1 on 2026-08-03 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0010_alter_gridimagedemo_grid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagedemo',
            name='cropping_blur',
        ),
        migrations.RemoveField(
            model_name='imagedemo',
            name='cropping_main',
        ),
        migrations.RemoveField(
            model_name='imagedemo',
            name='cropping_small',
        ),
    ]
