# Generated by Django 6.0.1 on 2026-02-18 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='google_access_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='google_refresh_token',
        ),
    ]
