from django.utils.translation import gettext as _

_('day_one')
_('day_other')
_('api-error-message')
_('adultsWithCount_one')
_('adultsWithCount_other')
_('childrenWithCount_one')
_('childrenWithCount_other')
_('adults_other')
_('Please, enter the arival date.')
_('availableDate')
_('There must be at least 1 guest.')
_('Days must be a number.')
_('CONTACTS')
_('locationSideText.one')
_('locationSideText.two')
_('Your booking request')
_('Available rooms')
_('No available rooms for these dates. Check the next available dates for booking below.')
_('index-title')
_('Vayots Dzor')
