"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from site_content.utils.get_translation_version import (
    get_translation_version,
)
from django.utils.translation import gettext_lazy as _
from pathlib import Path
import os
from dotenv import load_dotenv
import structlog
from dj_lite import sqlite_config
from google.oauth2 import service_account
from main.logging import shorten_exception
from corsheaders.defaults import default_headers

# from django.core.management.utils import get_random_secret_key

# new_key = get_random_secret_key()
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY")

ON_RENDER = os.environ.get("RENDER") == "true"
DEBUG = os.environ.get("DEBUG") == "True"
AUTH_USER_MODEL = "auth_app.User"
# if DEBUG:
#     SESSION_COOKIE_SAMESITE = "None"
#     CSRF_COOKIE_SAMESITE = "None"
#     SESSION_COOKIE_SECURE = False
#     CSRF_COOKIE_SECURE = False
# SESSION_COOKIE_DOMAIN = "backend.test"
ALLOWED_HOSTS = []
RENDER_EXTERNAL_HOSTNAME = os.environ.get("RENDER_EXTERNAL_HOSTNAME")
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)
else:
    ALLOWED_HOSTS = [
        "localhost",
        "0.0.0.0",
        "127.0.0.1",
        "backend.test",
        "192.168.11.53",
    ]
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = [
    "https://gh-demo-tr9j.onrender.com",
    "http://192.168.11.58:5173",
    "http://localhost:5173",
]
CORS_ALLOW_HEADERS = list(default_headers) + [
    "x-booking-token",
    "x-language",
    "content-type",
]
CSRF_TRUSTED_ORIGINS = []
if RENDER_EXTERNAL_HOSTNAME:
    CSRF_TRUSTED_ORIGINS.append(f"https://{RENDER_EXTERNAL_HOSTNAME}")


CLIENT_URL = os.environ.get("CLIENT_URL")
SITE_NAME = os.environ.get("SITE_NAME")

if ON_RENDER:
    SITE_DOMAIN = RENDER_EXTERNAL_HOSTNAME
else:
    SITE_DOMAIN = "http://0.0.0.0:8000"

# Application definition
INSTALLED_APPS = [
    "modeltranslation",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.admin",
    "whitenoise.runserver_nostatic",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    "main",
    "site_content",
    "auth_app",
    "demo",
    # "django_otp",
    # "django_otp.plugins.otp_static",
    # "django_otp.plugins.otp_totp",
    # "django_otp.plugins.otp_email",
    # "two_factor",
    "easy_thumbnails",
    "image_cropping",
    "rest_framework",
    "django_rest_passwordreset",
    "corsheaders",
    "django_filters",
    "django_extensions",
    "django_structlog",
]
SITE_ID = 1
# LOGIN_URL = "two_factor:login"
# LOGIN_REDIRECT_URL = "two_factor:profile"
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "main.middleware.RequestLanguageMiddleware",
    "main.middleware.ClientIPMiddleware",
    "django_structlog.middlewares.RequestMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    # "django_otp.middleware.OTPMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]
AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
]
REST_FRAMEWORK = {
    "DEFAULT_FILTER_BACKEND": ["django_filters.rest_framework.DjangoFilterBackend"],
    "DEFAULT_AUTHENTICATION_CLASSES": [],
    "DEFAULT_PERMISSION_CLASSES": ["rest_framework.permissions.IsAuthenticated"],
}
ROOT_URLCONF = "app.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            os.path.join(BASE_DIR, "templates"),
            os.path.join(BASE_DIR, "collectstatic/frontend"),
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "django.template.context_processors.request",
            ],
        },
    },
]

WSGI_APPLICATION = "app.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

if ON_RENDER:
    DB_PATH = Path("/var/data/db")
else:
    DB_PATH = BASE_DIR
DATABASES = {"default": sqlite_config(DB_PATH)}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"
LANGUAGES = [("en", _("English")), ("ru", _("Russian"))]
LOCALE_PATHS = [BASE_DIR / "locale"]


TRANSLATION_VERSION = get_translation_version()


TIME_ZONE = "UTC"

USE_I18N = True
USE_L10N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
MEDIA_BASE_URL = os.environ.get("MEDIA_BASE_URL") if ON_RENDER else ""

if ON_RENDER:
    MEDIA_URL = os.environ.get("MEDIA_BASE_URL") + "/media/"
else:
    MEDIA_URL = "/media/"
    MEDIA_ROOT = os.path.join(BASE_DIR, "media")

STATIC_URL = "/static/"
STATICFILES_DIRS = [
    BASE_DIR / "staticfiles",
]
STATIC_ROOT = BASE_DIR / "collectstatic/"

IMAGE_CROPPING_BACKEND = "image_cropping.backends.easy_thumbs.EasyThumbnailsBackend"
IMAGE_CROPPING_BACKEND_PARAMS = {}

THUMBNAIL_BASEDIR = "thumbnails"
# THUMBNAIL_MEDIA_ROOT = BASE_DIR / "collectstatic/media/thumbnails"
# THUMBNAIL_MEDIA_URL = "/thumbnails/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = os.environ.get("EMAIL_HOST")
EMAIL_PORT = int(os.environ.get("EMAIL_PORT"))
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD")
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL")

SERVER_EMAIL = os.environ.get("EMAIL_HOST_USER")

ALLOWED_SERVICES = []

# oauth/api services
GOOGLE_CLIENT_ID = os.environ.get("GOOGLE_CLIENT_ID")
GOOGLE_CLIENT_SECRET = os.environ.get("GOOGLE_CLIENT_SECRET")

ADMINS = ["ivfmn2@gmail.com", "house.shushan@gmail.com"]
MANAGERS = ["ivfmn2@gmail.com", "house.shushan@gmail.com"]

# CELERY_BROKER_URL = os.environ.get("REDIS_URL", "redis://127.0.0.1:6379/0")
# CELERY_ACCEPT_CONTENT = ["json"]
# CELERY_TASK_SERIALIZER = "json"
# CELERY_BROKER_TRANSPORT_OPTIONS = {
#     "socket_connect_timeout": 5,
#     "socket_timeout": 5,
# }
# CELERY_TASK_ALWAYS_EAGER = False
# CELERY_RESULT_BACKEND = "django-db"
# CELERY_TASK_TRACK_STARTED = True
# CELERY_TASK_TIME_LIMIT = 30

# DJANGO_STRUCTLOG_CELERY_ENABLED = True
if DEBUG:
    DJANGO_STRUCTLOG_MIDDLEWARE_LOG_LEVEL = "DEBUG"
else:
    DJANGO_STRUCTLOG_MIDDLEWARE_LOG_LEVEL = "WARNING"
LOGGING_LEVEL = os.environ.get("LOGGING_LEVEL", "WARNING")
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": LOGGING_LEVEL,
    },
}


structlog.configure(
    processors=[
        structlog.contextvars.merge_contextvars,
        structlog.processors.TimeStamper(fmt="iso"),
        structlog.processors.add_log_level,
        structlog.processors.format_exc_info,
        shorten_exception,
        structlog.processors.JSONRenderer(),
    ],
    logger_factory=structlog.stdlib.LoggerFactory(),
    wrapper_class=structlog.stdlib.BoundLogger,
    cache_logger_on_first_use=True,
)


# Google Cloud Storage
if ON_RENDER:
    CREDENTIAL_PATH = "/etc/secrets/storage-credentials.json"
else:
    CREDENTIAL_PATH = os.path.join(BASE_DIR, "storage-credentials.json")

GS_CREDENTIALS = service_account.Credentials.from_service_account_file(CREDENTIAL_PATH)

if ON_RENDER:
    STORAGE_BACKEND = "storages.backends.gcloud.GoogleCloudStorage"
    STORAGE_BACKEND_OPTIONS = {
        "bucket_name": os.environ.get("GOOGLE_CLOUD_STORAGE_BUCKET"),
        "project_id": os.environ.get("GOOGLE_CLOUD_PROJECT_NAME"),
        "credentials": GS_CREDENTIALS,
        "location": "media",
        "default_acl": None,
        "querystring_auth": False,
    }
else:
    STORAGE_BACKEND = "django.core.files.storage.FileSystemStorage"
    STORAGE_BACKEND_OPTIONS = {}

STORAGES = {
    "default": {
        "BACKEND": STORAGE_BACKEND,
        "OPTIONS": STORAGE_BACKEND_OPTIONS,
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
