from django.utils.translation import gettext as _

_('guests')
_('childrenWithCount_one')
_('childrenWithCount_other')
_('Maximum guests')
_('Select number of guests')
_('adults')
_('children')
_('Beds')
_('For one night')
_('Select guests')
_('Room selected')
_('No available rooms for these dates. Please check another date.')
_('Available rooms')
_('Selected guests')
_('Adults')
_('Children')
_('Book')
_('Something went wrong')
_('back to the main page')
_('adultsWithCount_one')
_('adultsWithCount_other')
_('reset')
_('continue')
_('Number of guests')
_('Please enter the arival date.')
_('Please enter correct date.')
_('availableDate')
_('There must be at least 1 guest.')
_('Nights must be a number.')
_('This is a test version of the project')
_('Site name')
_('About')
_('Rooms')
_('Contacts')
_('Location')
_('create_reservation')
_('dayWithCount_one')
_('dayWithCount_other')
_('Continue')
_('book')
_('Check-in date')
_('NightWithCount_one')
_('NightWithCount_other')
_('Open in Google Maps')
_('Open a written guide')
_('Shuttle from Yeghegnadzor')
_('No data')
_('Loading...')
_('wikipedia')
_('location link')
_('Your booking request')
_('date')
_('number of guests')
_('nights')
_('back to booking')
_('Your session has expired')
_('We could not verify your request. Please try again later.')
_('Your booking request has been submitted!')
_('booking-success-contact-msg')
_('Show available rooms')
_('edit reservation')
_('booking summary paragraph')
_('Email')
_('summary email help-text')
_('Guest name')
_('summary guest name help-text')
_('Message')
_('Please let us know the time of your arrival and any additional information related to your stay.')
_('submitting')
_('index-title')
_('Vayots Dzor')
_('Points of interest in the province')
